version: '3'
services:
  web:
    image: moj_server:latest
    depends_on:
      - database
      - php
    ports:
      - "80:8080"
    networks:
      - app-network

  php:
    image: moja_aplikacija:latest
    depends_on:
      - database
    networks:
      - app-network
  database:
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blah
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demoproject
    networks:
      - app-network

networks:
  app-network:
    driver: bridge